s3_uploder:
  data_path: "data/external"
  s3_bucket: "ragpipelinedata"
  s3_path: "ragpipelinedata/input_data"

s3_loader:
  local_path: "data/external"
  local_data: "data/raw"

chunk_data:
  chunk_size: 1000
  chunk_overlap: 100

store_data:
  collection_name: "rag_docs"
  field_name: "vector"
  embedding_model: "text-embedding-3-small"

retriever:
  relevant_chunks: 5
